version: "3.9"

services:
  spring-ai-chatbot:
    build: .
    container_name: spring-ai-chatbot
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always
