# spring.config.import=optional:file:.env[.properties]

spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.3
    transformers:
      embedding:
#        model: sentence-transformers/all-MiniLM-L6-v2   # local embedding model
        model: text-embedding-ada-002   # Use OpenAI's remote embedding model

    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
#      dimension: 384  # NOTE: this matches the MiniLM model output size
      dimension: 1536  # Ada-002 output size
  datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}


app:
  faq-path: ${HR_FAQ_PATH}
