version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: pgvector_db
    environment:
      POSTGRES_USER: vectorstore
      POSTGRES_PASSWORD: vectorstore
      POSTGRES_DB: vectorstore
    ports:
      - "15438:5432"
#    volumes:
      # Optional: Persist data on your local machine
#      - ./data:/var/lib/postgresql/data